[versions]

[libraries]

logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.12" }
slf-api = { module = "org.slf4j:slf4j-api", version = "2.0.16" }

[bundles]

logging = ["logback-classic", "slf-api"]
